title: Wellness CoP Toolkit
description: A practical toolkit for building wellness-centered communities of practice.
url: ""
baseurl: "/wellnesscop_dec"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
color_scheme: light
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

